from enum import Enum


class StrEnum(str, Enum):
    def __str__(self):
        return self.value


class Installs:
    class Field(StrEnum):
        application_id = 'application_id'
        click_datetime = 'click_datetime'
        click_id = 'click_id'
        click_ipv6 = 'click_ipv6'
        click_timestamp = 'click_timestamp'
        click_url_parameters = 'click_url_parameters'
        click_user_agent = 'click_user_agent'
        profile_id = 'profile_id'
        publisher_id = 'publisher_id'
        publisher_name = 'publisher_name'
        tracker_name = 'tracker_name'
        tracking_id = 'tracking_id'
        install_datetime = 'install_datetime'
        install_ipv6 = 'install_ipv6'
        install_receive_datetime = 'install_receive_datetime'
        install_receive_timestamp = 'install_receive_timestamp'
        install_timestamp = 'install_timestamp'
        is_reattribution = 'is_reattribution'
        is_reinstallation = 'is_reinstallation'
        match_type = 'match_type'
        appmetrica_device_id = 'appmetrica_device_id'
        city = 'city'
        connection_type = 'connection_type'
        country_iso_code = 'country_iso_code'
        device_locale = 'device_locale'
        device_manufacturer = 'device_manufacturer'
        device_model = 'device_model'
        device_type = 'device_type'
        google_aid = 'google_aid'
        ios_ifa = 'ios_ifa'
        ios_ifv = 'ios_ifv'
        mcc = 'mcc'
        mnc = 'mnc'
        operator_name = 'operator_name'
        os_name = 'os_name'
        os_version = 'os_version'
        windows_aid = 'windows_aid'
        app_package_name = 'app_package_name'
        app_version_name = 'app_version_name'


class Events:
    class Field(StrEnum):
        event_datetime = 'event_datetime'
        event_json = 'event_json'
        event_name = 'event_name'
        event_receive_datetime = 'event_receive_datetime'
        event_receive_timestamp = 'event_receive_timestamp'
        event_timestamp = 'event_timestamp'
        session_id = 'session_id'
        installation_id = 'installation_id'
        appmetrica_device_id = 'appmetrica_device_id'
        city = 'city'
        connection_type = 'connection_type'
        country_iso_code = 'country_iso_code'
        device_ipv6 = 'device_ipv6'
        device_locale = 'device_locale'
        device_manufacturer = 'device_manufacturer'
        device_model = 'device_model'
        device_type = 'device_type'
        google_aid = 'google_aid'
        ios_ifa = 'ios_ifa'
        ios_ifv = 'ios_ifv'
        mcc = 'mcc'
        mnc = 'mnc'
        operator_name = 'operator_name'
        original_device_model = 'original_device_model'
        os_name = 'os_name'
        os_version = 'os_version'
        profile_id = 'profile_id'
        windows_aid = 'windows_aid'
        app_build_number = 'app_build_number'
        app_package_name = 'app_package_name'
        app_version_name = 'app_version_name'
        application_id = 'application_id'


class Sessions:
    class Field(StrEnum):
        session_id = 'session_id'
        session_start_datetime = 'session_start_datetime'
        session_start_receive_datetime = 'session_start_receive_datetime'
        session_start_receive_timestamp = 'session_start_receive_timestamp'
        session_start_timestamp = 'session_start_timestamp'
        appmetrica_device_id = 'appmetrica_device_id'
        city = 'city'
        connection_type = 'connection_type'
        country_iso_code = 'country_iso_code'
        device_ipv6 = 'device_ipv6'
        device_locale = 'device_locale'
        device_manufacturer = 'device_manufacturer'
        device_model = 'device_model'
        device_type = 'device_type'
        google_aid = 'google_aid'
        ios_ifa = 'ios_ifa'
        ios_ifv = 'ios_ifv'
        mcc = 'mcc'
        mnc = 'mnc'
        operator_name = 'operator_name'
        original_device_model = 'original_device_model'
        os_name = 'os_name'
        os_version = 'os_version'
        profile_id = 'profile_id'
        windows_aid = 'windows_aid'
        app_build_number = 'app_build_number'
        app_package_name = 'app_package_name'
        app_version_name = 'app_version_name'
        application_id = 'application_id'
